production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true

staging:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true

standalone:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      max_retries_on_connection_failure: 3
      persist_in_safe_mode: true
      skip_version_check: true

development:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      max_retries_on_connection_failure: 3
      persist_in_safe_mode: true
      skip_version_check: true

test:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      max_retries_on_connection_failure: 3
      persist_in_safe_mode: true
      skip_version_check: true
